### ISSUE TITLE
no chart showing in Jupyter

### ISSUE THREAD

**Issue by daoyanghu** [TechfaneTechnologies/PyTvLwCharts#10]
there's no chart showing in Jupyter currently. only "made by DrJuneMoone". I double checked, the data is correct.

**Comment by MooneDrJune** [comment]
> there's no chart showing in Jupyter currently. only "made by DrJuneMoone". I double checked, the data is correct.

There was an update in progress. But Its Woking now as intended.

Please follow this [notebook](https://colab.research.google.com/drive/1ApN2CHWNUZsKNxiqYjpT9glQdwt1c6qN?usp=sharing) for ready references. 

Update Was To include Legend On Charts.

![image](https://user-images.githubusercontent.com/96371033/220195907-1285159a-f398-4105-baa4-6a9968b915c4.png)
