### ISSUE TITLE
not showing chart in local jupyter notebook

### ISSUE THREAD

**Issue by daoyanghu** [TechfaneTechnologies/PyTvLwCharts#11]
hi, i can see the chart working in Colab, however in local environment, it's not showing. do you know the reason why? is this related to javascript execution permission?

**Comment by MooneDrJune** [comment]
> hi, i can see the chart working in Colab, however in local environment, it's not showing. do you know the reason why? is this related to JavaScript execution permission?

I am aware of it, though it can work, but it's getting complicated and not all features can be utilized without using extensions like ` Voilà` .

However, on local environment it works with ` Voilà` rendering _(i.e. With Jupiter Lab you can opt to render your notebook with ` Voilà`)_,or you can use the flask mode to open the chart in browser with localhost address.

Even Google Colab can be connected to local environment.
