### ISSUE TITLE
How to mark Support and Resistance horizontal lines or zones onto the Candlestick chart?

### ISSUE THREAD

**Issue by vinayyak** [TechfaneTechnologies/PyTvLwCharts#16]
Hi, just started using this library and everything looks great! just wanted to know how I could add horizontal lines onto the chart to mark support and resistance zones programmatically. I already have the data for these zones, I just want to mark them.  I tried to use the `mark_line` function to do so but is there a better way of marking the zones?

**Comment by axinos** [comment]
**mark_line** only seems to allow to draw horizontal lines across the whole chart, i.e. there are no start and end points.
Like you, @vinayyak, I am looking for a function which allows to draw a line between two points (x0,y0) and (x1,y1) in my case (horizontal line) y0=y1. 
I could not find such function despite hour long research, this repo unfortunately seems to be abandoned...
