### ISSUE TITLE
Impossible to add annotations

### ISSUE THREAD

**Issue by electrotiti** [TechfaneTechnologies/PyTvLwCharts#4]
When you try to add an annotations with this code:
```
DailyChart = DailyChart.mark_annotation(data=pd.DataFrame({'time':{1: 1656666900}, 'position':{1: 'belowBar'}, 'color': {1: '#2196F3'}, 'shape': {1:'arrowUp'}, 'text': {1:'TEST'}}))
```
You get this error:
```
AttributeError: 'Series' object has no attribute 'markers'
```
This is due to an typing error on **_markers** variable, you should replace on line 140 this line:
```
self.markers.append(markers)
```

by this:
```
self._markers.append(markers)
```

By the way when you change the variable name and test again you get this error:
```
TypeError: DataFrame.to_dict() got an unexpected keyword argument 'date_format'
```
This is because the argument **date_format** don't seems to exist in to_dict function.

You should change this line number 106 by removing this argument:

```
    } for marker in self._data.to_dict(orient='records')]
```

FYI: I'm not allow to create a Pull request on you repo, so I did a fork about this: https://github.com/electrotiti/pytvlwcharts

**Comment by MooneDrJune** [comment]
> When you try to add an annotations with this code:
> 
> ```
> DailyChart = DailyChart.mark_annotation(data=pd.DataFrame({'time':{1: 1656666900}, 'position':{1: 'belowBar'}, 'color': {1: '#2196F3'}, 'shape': {1:'arrowUp'}, 'text': {1:'TEST'}}))
> ```
> 
> You get this error:
> 
> ```
> AttributeError: 'Series' object has no attribute 'markers'
> ```
> 
> This is due to an typing error on **_markers** variable, you should replace on line 140 this line:
> 
> ```
> self.markers.append(markers)
> ```
> 
> by this:
> 
> ```
> self._markers.append(markers)
> ```
> 
> By the way when you change the variable name and test again you get this error:
> 
> ```
> TypeError: DataFrame.to_dict() got an unexpected keyword argument 'date_format'
> ```
> 
> This is because the argument **date_format** don't seems to exist in to_dict function.
> 
> You should change this line number 106 by removing this argument:
> 
> ```
>     } for marker in self._data.to_dict(orient='records')]
> ```
> 
> FYI: I'm not allow to create a Pull request on you repo, so I did a fork about this: https://github.com/electrotiti/pytvlwcharts

Thanks for identifying the issue. your commits has been merged with https://github.com/TechfaneTechnologies/pytvlwcharts/pull/5
