### ISSUE TITLE
Price Line and Set marker

### ISSUE THREAD

**Issue by tabatabaei** [TechfaneTechnologies/PyTvLwCharts#6]
I found this code on the Jinja template which creates the price lines and sets the markers in the chart but I could not find any related function. How can I use this ability in this library? 

       chart_series.setMarkers(
         {{ series.markers }}
       );
       {% for price_line in series.price_lines %}
       chart_series.createPriceLine({{ price_line }});
       chart.subscribeCrosshairMove(param => {
           if (param.time) console.log(param.seriesPrices.get(chart_series))
        });
       {% endfor %}

**Comment by MooneDrJune** [comment]
> I found this code on the Jinja template which creates the price lines and sets the markers in the chart but I could not find any related function. How can I use this ability in this library?
> 
> ```
>    chart_series.setMarkers(
>      {{ series.markers }}
>    );
>    {% for price_line in series.price_lines %}
>    chart_series.createPriceLine({{ price_line }});
>    chart.subscribeCrosshairMove(param => {
>        if (param.time) console.log(param.seriesPrices.get(chart_series))
>     });
>    {% endfor %}
> ```

Do These..
`%pip install --quiet -U git+https://github.com/TechfaneTechnologies/pytvlwcharts.git`
![image](https://user-images.githubusercontent.com/96371033/205879798-430ff1bf-b22b-4e68-995d-a46835ed5440.png)

```python
from pytvlwcharts import *
import pandas as pd
```
have your data ready in a dataframe
![image](https://user-images.githubusercontent.com/96371033/205880561-a2755cc8-e82b-42c3-a127-413605b66fc1.png)

Then Do This
```python
chart = Chart(
    width = 1360,
    height = 400,
    time_scale=TimeScaleOptions(
        seconds_visible=True,
        time_visible=True)
    )
chart.mark_line(data=df, title='Banknifty', color='#2962FF', lineWidth=LineWidth.LINEWIDTH_3, lineType=0, lineStyle=LineStyle.LINESTYLE_0, lastPriceAnimation=True)
```
It will plot the line series like this
![image](https://user-images.githubusercontent.com/96371033/205880824-b0b218c6-50a4-4415-8734-71d5d20eb706.png)
