### ISSUE TITLE
is there a way to change how precise you want the price format to be?

### ISSUE THREAD

**Issue by ppokhare** [TechfaneTechnologies/PyTvLwCharts#8]
with JS lightweight charts  one can change how precise you want the price to be by:

 priceFormat: { precision: 6, minMove: 0.000001 } 

but I don't see that option here. 

In the below example, 2 decimal points  does not tell enough information
<img width="514" alt="Screenshot 2023-01-18 at 21 33 22" src="https://user-images.githubusercontent.com/50219207/213363374-497a52f8-15e0-4bb6-8b65-be8e55bbc593.png">

**Comment by MooneDrJune** [comment]
> priceFormat:

You Can Pass the Parameters while marking series.

refer this notebook for more details on how to use it. https://colab.research.google.com/drive/1LT3qd6SNw53bRfew1L2R7zlA73RS2FWJ?usp=sharing

![image](https://user-images.githubusercontent.com/96371033/213373471-162fdea0-7026-4890-8415-88528da3012c.png)



![image](https://user-images.githubusercontent.com/96371033/213372991-710fde44-8c0e-4fda-be5c-10f439145ce3.png)
