### ISSUE TITLE
is there a way to add series marker?

### ISSUE THREAD

**Issue by ppokhare** [TechfaneTechnologies/PyTvLwCharts#9]
Is there a way  to add a series marker like this: https://tradingview.github.io/lightweight-charts/tutorials/how_to/series-markers#full-example

I don't see any example but I can see there is a mark_annotation function inside the Series call. Can you show an example of how to add markers?

**Comment by MooneDrJune** [comment]
> Is there a way to add a series marker like this: https://tradingview.github.io/lightweight-charts/tutorials/how_to/series-markers#full-example
> 
> I don't see any example but I can see there is a mark_annotation function inside the Series call. Can you show an example of how to add markers?

Yes, you can use `mark_annotation` function to add your markers to the series of your choice.

Refer [This Notebook](https://colab.research.google.com/drive/1LT3qd6SNw53bRfew1L2R7zlA73RS2FWJ?usp=sharing) for an example.

![image](https://user-images.githubusercontent.com/96371033/216820876-77414f1b-eea8-4d08-a43f-61979cec413b.png)
